services:
  backend:
    build: ./Backend
    env_file:
      - ./Backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    volumes:
     - ./Frontend/vite-project:/app
     - /app/node_modules
