services:
  db:
    image: postgres:15-alpine
    restart: always
  backend:
    build: ./Backend
    env_file:
      - ./Backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    depends_on:
      - db

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    volumes:
     - ./Frontend/vite-project:/app
     - /app/node_modules
