name: CI/CD Pipeline

on:
  push:
    branches: [ "CICD" ] # 當推送到 CICD 分支時觸發

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
      - name: preset
        uses: actions/checkout@v4
      
      - name: Create .env File
        run: |
          echo "POSTGRES_USER=user" > Backend/.env
          echo "POSTGRES_PASSWORD=password" >> Backend/.env
          echo "POSTGRES_DB=mydatabase" >> Backend/.env
          echo "DATABASE_URL=postgresql://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@db:5432/\${POSTGRES_DB}" >> Backend/.env
          echo "JWT_SECRET_KEY=123" >> Backend/.env
          echo "REGISTER_KEY=123" >> Backend/.env
          echo "ADMIN_ACCOUNT=user" >> Backend/.env
          echo "ADMIN_PASSWORD=test" >> Backend/.env
          echo "APP_URL=http://127.0.0.1:5000" >> Backend/.env
          echo "ADMIN=1" >> Backend/.env
          echo "GUEST=5" >> Backend/.env
          echo "GUEST_MODE=True" >> Backend/.env
          
      - name: Build > pytest
        run: |
          echo "Building and starting services..."
          make build
          
          sleep 50
          
          echo "Running Pytests..."
          make test
          
      - name: docker compose down
        if: always()
        run: |
          make down

  env_injection_check:
    name: Injection Check
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: preset
        uses: actions/checkout@v4

      - name: Inject Secrets
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          REGISTER_KEY: ${{ secrets.REGISTER_KEY }}
          CORS_ORIGINS: ${{ secrets.CORS_ORIGINS }}
          ADMIN_ACCOUNT: ${{ secrets.ADMIN_ACCOUNT }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          APP_URL: ${{ secrets.APP_URL }}
          ADMIN: ${{ secrets.ADMIN }}
          GUEST: ${{ secrets.GUEST }}
          GUEST_MODE: ${{ secrets.GUEST_MODE }}
          
        run: |
          echo "--- 生產環境參數成功注入 ---"
          echo "APP_URL: ${APP_URL:0:10}..."
          echo "CORS_ORIGINS: ${CORS_ORIGINS:0:10}"
          echo "GUEST_MODE: ${GUEST_MODE:0:2}"
          
          echo "--- 參數注入與檢查完成 ---"